# Generated by Django 6.0.1 on 2026-01-20 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], max_length=10)),
                ('fps', models.IntegerField(default=30)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('has_system_audio', models.BooleanField(default=False)),
                ('has_microphone', models.BooleanField(default=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(default='video/webm', max_length=100)),
                ('codec', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('original_webm', 'Original WebM'), ('converted_mp4', 'Converted MP4'), ('audio_extract', 'Extracted Audio')], max_length=20)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_bucket', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recordings.recording')),
            ],
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['-created_at'], name='recordings__created_0ddc66_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['user', '-created_at'], name='recordings__user_id_d67826_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingfile',
            index=models.Index(fields=['recording', 'file_type'], name='recordings__recordi_72253d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingfile',
            unique_together={('recording', 'file_type')},
        ),
    ]
