# Generated by Django 6.0.1 on 2026-01-20 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('language_detected', models.CharField(default='en', max_length=10)),
                ('num_speakers', models.IntegerField(default=0)),
                ('audio_duration_seconds', models.FloatField()),
                ('processing_time_seconds', models.FloatField()),
                ('deepgram_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='recordings.recording')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('summary', 'Summary'), ('action_items', 'Action Items'), ('key_points', 'Key Points'), ('sentiment', 'Sentiment Analysis')], max_length=20)),
                ('result_data', models.JSONField(default=dict)),
                ('result_text', models.TextField()),
                ('model_version', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField()),
                ('gemini_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='recordings.recording')),
            ],
            options={
                'indexes': [models.Index(fields=['recording', 'analysis_type'], name='analysis_ai_recordi_c6529c_idx')],
                'unique_together': {('recording', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time_seconds', models.FloatField()),
                ('end_time_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('speaker_id', models.IntegerField(blank=True, null=True)),
                ('speaker_label', models.CharField(blank=True, max_length=50)),
                ('words', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='analysis.transcription')),
            ],
            options={
                'ordering': ['start_time_seconds'],
                'indexes': [models.Index(fields=['transcription', 'start_time_seconds'], name='analysis_tr_transcr_efacaf_idx'), models.Index(fields=['speaker_id'], name='analysis_tr_speaker_407347_idx')],
            },
        ),
    ]
